[build.environment]
  NODE_VERSION = "12.18.3"
  YARN_VERSION = "1.22.5"
  NPM_VERSION = "6.14.6"
  
  command = "yarn build" # the command you run to build this file
  functions = "built-lambda" # netlify-lambda builds to this folder AND Netlify reads functions from here
  publish = "build" # create-react-app builds to this folder, Netlify should serve all these files statically
